# Generated by Django 5.0.11 on 2025-04-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_test_total_marks_alter_student_user_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='marks',
            new_name='marks_got',
        ),
    ]
