# Generated by Django 5.0.11 on 2025-04-29 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.CharField(default=datetime.datetime(2025, 4, 29, 10, 59, 17, 490413), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='monther_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
