# Generated by Django 5.0.11 on 2025-04-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_student_address_student_dob_student_father_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'student')},
        ),
    ]
