# Generated by Django 5.0.11 on 2025-04-30 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='standard',
        ),
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.subjects'),
        ),
    ]
