# Generated by Django 5.0.11 on 2025-04-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_remove_test_standard_test_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='standard',
        ),
    ]
