# Generated by Django 5.0.11 on 2025-04-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_remove_marks_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.standard'),
        ),
    ]
