# Generated by Django 5.0.11 on 2025-05-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_alter_attendance_student_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
