# Generated by Django 5.0.11 on 2025-05-11 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.standard')),
            ],
        ),
    ]
