# Generated by Django 5.0.11 on 2025-05-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0020_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_left',
            field=models.PositiveIntegerField(default=10000),
            preserve_default=False,
        ),
    ]
