# Generated by Django 5.0.11 on 2025-05-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_student_fee_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_fee',
            field=models.PositiveIntegerField(default=10000),
            preserve_default=False,
        ),
    ]
